### PR TITLE
Introduced several minor additions

### PR DESCRIPTION
**Pull request by garrett-eclipse**
Hello,

I wanted to merge some code from my remove-comments.php script attached;
[remove-comments.php.zip](https://github.com/solarissmoke/disable-comments/files/263945/remove-comments.php.zip)

Below is a list of items added;
1. Disabling the Comments, Discussion and Trackbacks Metaboxes (#29)
2. Emptying the Comments_Array
3. Removing the 'Turn comments on and off' link in the Wordpress Welcome (#30)
4. Removing the 'Comments RSS' link within the Meta Widget (#31)

Let me know if you find any issues with these changes.

Thanks

### CODE REVIEW

**Comment by garrett-eclipse** [comment]
I've also added the Delete Comments tool functionality;
5. Provide a purge tool for bulk deleting all comments (#33)

**Comment by solarissmoke** [comment]
I'm closing this PR as most of the changes has been incorporated in separate individual PRs for each issue. There is still one open for the delete comments functionality.

**Comment by garrett-eclipse** [comment]
Thanks @solarissmoke, sorry for the initial mess with the massive PR...
That remaining PR for delete comments should be good to go here;
https://github.com/solarissmoke/disable-comments/pull/37

**Comment by solarissmoke** [comment]
There are a couple of small issues with the PR which need to be addressed before we can merge - I just haven't had time to review properly. Will try and do that soon.

**Comment by garrett-eclipse** [comment]
Thanks @solarissmoke, just hit me up with any tweaks needed and I'll try and make some time for updates. Cheers

**Pull request closed without merging**
