### PR TITLE
Add ability to enable Discussions Settings when all Comments disabled

### PR DESCRIPTION
**Pull request by garrett-eclipse**
This introduces the ability to enable the Discussions Settings when Disable Comments is set to Everything. 

Originally this was to enable the Comments Blacklist for CF7 when all comments are disabled;
https://contactform7.com/comment-blacklist/

In addition to this with the Discussions Settings enabled an admin is able to control Avatar settings which when comments are disabled still apply to logged in users;
screen shot 2018-06-27 at 7 04 54 pm

Code to enable this setting in wp-config.php;
```
/* Disable Comments - Enable Discussions Settings */
define( 'DISABLE_COMMENTS_ALLOW_DISCUSSION_SETTINGS', true );
```

Fix for #48

### CODE REVIEW

**Comment by solarissmoke** [comment]
This looks good - could you please add units test to verify that this new constant works when present/missing? 

Mocking constants in phpunit is pretty ugly - I think you will have to create a new test class and then set [`$preserveGlobalState = false` and `$runTestInSeparateProcess = true`](http://queirozf.com/entries/error-message-constant-already-defined-when-using-phpunit), along with reloading the bootstrap code in `setUp()`.

**Comment by garrett-eclipse** [comment]
For sure sorry I missed this initially. I just committed the tests I'm writing. Sadly it looks like I missed the mark with Travis so am taking a look through.

Firstly tests on discussion_settings_allowed fail with Fatal as it's private. Should I make it public? Or is there a way to test private methods?
PHP Fatal error:  Call to private method Disable_Comments::discussion_settings_allowed() from context 'AllowDiscussionSettingsTestCase' in /home/travis/build/solarissmoke/disable-comments/tests/test-plugin.php on line 196

The other is a warning but seems it may always have been present;
Warning: The use statement with non-compound name 'PHPUnit_Framework_TestCase' has no effect in /home/travis/build/solarissmoke/disable-comments/tests/test-plugin.php on line 2

**Comment by garrett-eclipse** [comment]
Sorry for the commit clutter @solarissmoke I'm going to come back and clean that up.
If you don't mind taking a look at the test attempts I'd appreciate some pointers as I haven't written them before. I attempted several different approaches but kept hitting walls.
I appreciate your thoughts, thanks

**Comment by solarissmoke** [comment]
Sorry for the delay in reviewing this. I have spent a couple of hours trying to find a sane way to test this, and am struggling. I can't work out how to populate the admin menu before then testing that our code modifies it. Writing integration tests for WordPress really isn't straightforward, and I don't have the time/inclination to look into this for much longer. 

I'd suggest you just drop the tests from this PR. It is not a change that affects how comments are processed etc, and so we're going to have to live without tests for now.

**Comment by garrett-eclipse** [comment]
Thanks @solarissmoke I appreciate you taking a stab at it there, I tried some more locally without any luck. Sorry for the convoluted branch, the latest commit reverts prior to Unit Testing and I've re-conducted my user testing with these changes. I seem to have made Travis happy again as well.

**Comment by garrett-eclipse** [comment]
Thanks @solarissmoke

**Pull request merged**
